import sys, os
sys.stdout.reconfigure(encoding='utf-8')

report = []
report.append('=' * 78)
report.append('  PPT-READY MATERIAL: IntelliOps Knowledge Dedup + Aggregation')
report.append('  Aim: Solve high-frequency alert knowledge duplication via Skill distillation')
report.append('=' * 78)
report.append('')

report.append('---')
report.append('## Architecture Overview (3 new modules + 2 modified files)')
report.append('')
report.append('`')
report.append('run_postmortem_agent()')
report.append('  |')
report.append('  |-- 1. KnowledgeDistiller (existing, unchanged)')
report.append('  |     LLM distills 5 asset types from postmortem')
report.append('  |')
report.append('  |-- 2. knowledge_deduplicator [NEW]')
report.append('  |     |- Semantic dedup (cosine similarity)')
report.append('  |     |- Merge into existing entries')
report.append('  |     |- Track frequency per pattern')
report.append('  |')
report.append('  |-- 3. DB.upsert_knowledge (existing)')
report.append('  |')
report.append('  |-- 4. pattern_aggregator [NEW]')
report.append('  |     |- LLM batch refinement of high-freq patterns')
report.append('  |     |- Threshold calibration suggestions')
report.append('  |     |- Auto-remediation readiness scoring')
report.append('  |')
report.append('  |-- 5. skill_updater [NEW]')  
report.append('           |- Inject mature patterns into SKILL.md ref files')
report.append('           |- Create auto-remediation SKILL.md at readiness >= 70%')
report.append('`')
report.append('')

report.append('---')
report.append('## 5 Asset Types with Specialized Merge Strategies')
report.append('')
report.append('| Asset Type | Merge Strategy |')
report.append('|-----------|----------------|')
report.append('| root_cause_rules | Average confidence, union conditions, append sources |')
report.append('| sop_templates | Keep longest steps, union unique steps |')
report.append('| warning_signals | Escalate severity upward, merge sources |')
report.append('| script_recommendations | Keep longer/more complete code snippet |')
report.append('| key_learnings | Set-based dedup (unique strings only) |')
report.append('')

report.append('---')
report.append('## Configurable Thresholds (env vars, no code changes)')
report.append('')
report.append('| Variable | Default | Meaning |')
report.append('|----------|---------|---------|')
report.append('| KNOWLEDGE_MERGE_THRESHOLD | 0.82 | Cosine >= merge into existing |')
report.append('| KNOWLEDGE_VARIANT_THRESHOLD | 0.65 | Cosine >= flag as variant |')
report.append('| KNOWLEDGE_STORE_THRESHOLD | 0.35 | Cosine <= store as new entry |')
report.append('| KNOWLEDGE_HIGH_FREQ_THRESHOLD | 5 | Incidents >= trigger batch refine |')
report.append('')

report.append('---')
report.append('## Refined Pattern Output Schema')
report.append('')
report.append('| Field | Description |')
report.append('|-------|-------------|')
report.append('| canonical_pattern | Merged authoritative pattern (LLM refined) |')
report.append('| merged_conditions | Deduplicated union of trigger conditions |')
report.append('| confidence | Weighted average confidence |')
report.append('| auto_remediation_readiness | 0-1 score for automation viability |')
report.append('| threshold_calibrations | Monitoring threshold adjustment suggestions |')
report.append('| cross_service_pattern | Cross-service cascade description |')
report.append('')

report.append('---')
report.append('## SKILL Hot-Update Mapping')
report.append('')
report.append('| Asset Type | Target File |')
report.append('|-----------|------------|')
report.append('| root_cause_rules | src/skill/incident-diagnosis/references/root-cause-patterns.md |')
report.append('| warning_signals | src/skill/incident-diagnosis/references/diagnosis-api.md |')
report.append('| sop_templates | src/skill/script-operations/references/risk-matrix.md |')
report.append('| script_recommendations | src/skill/script-operations/references/risk-matrix.md |')
report.append('| (readiness >= 0.7) | src/skill/auto-xxx/SKILL.md (auto-generated) |')
report.append('')

report.append('---')
report.append('## Demo: 6 Incidents, 1 Pattern (Connection Pool Exhaustion)')
report.append('')
report.append('| Incident | Root Cause | Confidence |')
report.append('|----------|-----------|-----------|')
report.append('| inc-001 | Payment gateway DB pool exhausted, peak load | 85% |')
report.append('| inc-002 | Order service DB pool exhausted, peak traffic | 78% |')
report.append('| inc-003 | Core accounting pool undersized, batch | 91% |')
report.append('| inc-004 | Cache service connection leak | 82% |')
report.append('| inc-005 | API gateway vs backend pool mismatch | 79% |')
report.append('| inc-006 | Pool not re-tuned after container migration | 88% |')
report.append('')

report.append('---')
report.append('## Before vs After Comparison')
report.append('')
report.append('| Dimension | Traditional Approach | With Skill Dedup System |')
report.append('|-----------|--------------------|------------------------|')
report.append('| N same-type incidents | N redundant entries | ~N/3 refined patterns |')
report.append('| High-freq alert quality | Degrades (noise) | Improves (refinement) |')
report.append('| AI response to recurring | Loads N similar cases | Loads 1 authoritative pattern |')
report.append('| Monitoring thresholds | Manual tuning | Auto-generated calibration |')
report.append('| Knowledge to Skill | Manual copy/paste | Auto hot-update |')
report.append('')

report.append('---')
report.append('## Key Design Decisions')
report.append('')
report.append('1. Non-blocking: Dedup failure does not block postmortem return')
report.append('2. Dual path: LLM + heuristic fallback (graceful degradation)')
report.append('3. Incremental: No KB rebuild needed, works from day 1')
report.append('4. Maturity ladder: raw -> deduped -> merged -> refined -> SKILL')
report.append('5. Configurable: All thresholds via env vars')
report.append('')

report.append('---')
report.append('## Code Stats')
report.append('')
report.append('| File | Lines | Purpose |')
report.append('|------|-------|---------|')
report.append('| knowledge_deduplicator.py | 360 | Semantic dedup + merge + freq tracking |')
report.append('| pattern_aggregator.py | 310 | LLM + heuristic batch refinement |')
report.append('| skill_updater.py | 260 | SKILL.md ref injection + auto-skill |')
report.append('| incident_pipeline.py (mod) | +45 | Integration hook |')
report.append('| db.py (mod) | +12 | list_knowledge + delete_knowledge list |')
report.append('| Total | ~987 | 3 new modules + 2 modified files |')
report.append('')

report.append('=' * 78)
report.append('  END OF PPT MATERIAL')
report.append('=' * 78)

output = '\n'.join(report)
print(output)

outpath = os.path.join(os.path.dirname(__file__), '..', 'PPT_MATERIAL.md')
with open(outpath, 'w', encoding='utf-8') as f:
    f.write(output)
print()
print(f'Written to: {outpath}')

